name: "Feature Request"
description: "Suggest a new feature or enhancement."
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Please provide details about the feature you would like to see.
  - type: input
    id: summary
    attributes:
      label: "Feature Summary"
      description: "Briefly summarize the feature."
      placeholder: "Short summary"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why do you want this feature? What problem does it solve?"
      placeholder: "Describe the motivation or problem."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution or feature in detail."
      placeholder: "Describe the solution, workflow, or UI changes."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternatives?"
      placeholder: "List any alternative solutions or features."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, or references."
      placeholder: "Additional information"
    validations:
      required: false
