name: "Infrastructure Issue"
description: "Report a problem or request a change related to infrastructure."
title: "[Infra] "
labels: ["infrastructure", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Infrastructure Issue

        Please fill out the following details to help us address your infrastructure issue.
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Which environment is affected? (e.g., dev, staging, prod)"
      placeholder: "dev / staging / prod"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Issue Description"
      description: "Describe the infrastructure issue in detail."
      placeholder: "Describe the problem, error messages, etc."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe the expected behavior."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context, logs, or screenshots about the issue."
      placeholder: "Additional information"
    validations:
      required: false
