name: deploy-infrastructure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to validate the application infrastructure for"
        required: true
        type: string

    secrets:
      AZURE_TENANT_ID:
        description: "The Azure tenant ID to use for authentication to Azure for deployment"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "The Azure subscription ID to use for authentication to Azure for deployment"
        required: true
      AZURE_CLIENT_ID:
        description: "The Azure client ID to use for authentication to Azure for deployment"
        required: true
      FOUNDRY_USERNAME:
        description: "The Foundry username to use to download the Foundry VTT licence"
        required: true
      FOUNDRY_PASSWORD:
        description: "The Foundry password to use to download the Foundry VTT licence"
        required: true
      FOUNDRY_ADMIN_KEY:
        description: "The Foundry admin key to use for authentication to Foundry"
        required: true

jobs:
  deploy-infrastructure:
    name: Deploy ${{ inputs.ENVIRONMENT }} Infrastructure
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    env:
      # Required for azd to authenticate with Azure using Federated Credentials
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Required for azd to provision the infrastructure
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}

      # Optional azd parameters when using Federated Credentials
      AZURE_PRINCIPAL_ID_TYPE: 'ServicePrincipal'

      # Foundry secrets as environment variables
      FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
      FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
      FOUNDRY_ADMIN_KEY: ${{ secrets.FOUNDRY_ADMIN_KEY }}

      # Environment variables for azd
      AZURE_APP_SERVICE_PLAN_SKUNAME: ${{ vars.AZURE_APP_SERVICE_PLAN_SKUNAME }}
      AZURE_COMPUTE_SERVICE: ${{ vars.AZURE_COMPUTE_SERVICE }}
      AZURE_DEPLOY_DDB_PROXY: ${{ vars.AZURE_DEPLOY_DDB_PROXY }}
      AZURE_DEPLOY_DIAGNOSTICS: ${{ vars.AZURE_DEPLOY_DIAGNOSTICS }}
      AZURE_DEPLOY_NETWORKING: ${{ vars.AZURE_DEPLOY_NETWORKING }}
      AZURE_STORAGE_RESOURCE_LOCK_ENABLED: ${{ vars.AZURE_STORAGE_RESOURCE_LOCK_ENABLED }}
      AZURE_CONTAINER_INSTANCE_CPU: ${{ vars.AZURE_CONTAINER_INSTANCE_CPU }}
      AZURE_CONTAINER_INSTANCE_MEMORY_IN_GB: ${{ vars.AZURE_CONTAINER_INSTANCE_MEMORY_IN_GB }}
      AZURE_STORAGE_PUBLIC_ACCESS: ${{ vars.AZURE_STORAGE_PUBLIC_ACCESS }}
      FOUNDRY_DOCKER_IMAGE_TAG: ${{ vars.FOUNDRY_DOCKER_IMAGE_TAG }}

      # Set AZD_PROVISION_NO_STATE to true to force reprovisioning of the infrastructure
      AZD_PROVISION_NO_STATE: ${{ vars.AZD_PROVISION_NO_STATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install azd
        uses: Azure/setup-azd@v2.2.0

      - name: Authenticate azd (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Provision Infrastructure
        run: |
          args="--no-prompt"
          if [ "${AZD_PROVISION_NO_STATE}" = "true" ]; then
            args="$args --no-state"
          fi
          azd provision $args
