name: Set Build Variables

on:
  workflow_call:
    outputs:
      BUILD_VERSION:
        description: The build version
        value: ${{ jobs.set-build-variables.outputs.build_version }}

jobs:
  set-build-variables:
    name: Set build variables
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.build_version.outputs.GitVersion_FullSemVer }}
      FullSemVer: ${{ steps.build_version.outputs.GitVersion_FullSemVer }}
      MajorMinorPatch: ${{ steps.build_version.outputs.GitVersion_MajorMinorPatch }}
      SemVer: ${{ steps.build_version.outputs.GitVersion_SemVer }}
      NuGetVersion: ${{ steps.build_version.outputs.GitVersion_NuGetVersionV2 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1
        with:
          versionSpec: "6.3.x"

      - name: Determine Version
        id: build_version
        uses: gittools/actions/gitversion/execute@v4.0.1
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display GitVersion outputs
        run: |
          echo "FullSemVer: ${{ steps.build_version.outputs.GitVersion_FullSemVer }}"
          echo "MajorMinorPatch: ${{ steps.build_version.outputs.GitVersion_MajorMinorPatch }}"
          echo "SemVer: ${{ steps.build_version.outputs.GitVersion_SemVer }}"
          echo "NuGetVersion: ${{ steps.build_version.outputs.GitVersion_NuGetVersionV2 }}"
